import Head from 'next/head'
import Header from './header'
import 'bootstrap/dist/css/bootstrap.min.css';
import Headerr from './pagess/headerr';
import Carousel from './pagess/foodSlider'
import TeamResturan from './pagess/teamResturan';
import Carusel from './pagess/fodSlider';
import MediaCard from './Cards/cards';
import Advertisement from './pagess/advertisement';
import BasicTimeline from './pagess/stan';
import FooterPagePro from './pagess/footer';


export default function Home() {
  return (
    <div >
      <Head>
        <title>Resturant week || akromov14</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com"/>
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin/>
        <link href="https://fonts.googleapis.com/css2?family=Inconsolata:wght@600&display=swap" rel="stylesheet"></link>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link href="https://fonts.googleapis.com/css2?family=Anton&display=swap" rel="stylesheet"></link>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link href="https://fonts.googleapis.com/css2?family=Anton&family=Karantina&display=swap" rel="stylesheet"></link>
      </Head>
      <main >
         <div className="container">
            <Header />
            <Headerr />
         </div>
         <Carousel />
         <TeamResturan />
         <Carusel />
         <MediaCard />
         <BasicTimeline />
         <Advertisement />
         <FooterPagePro />
      </main>
    </div>
  )
}
